name: Build OpenMRS Maven Module

on:
  workflow_call:
    inputs:
      java_versions:
        description: 'Java versions to build against'
        type: string
      main_java_version:
        description: 'Java version to use for publishing artifacts'
        type: string
      java_distribution:
        description: 'Java distribution'
        type: string
        default: 'temurin'
      maven_args:
        description: 'Maven Arguments'
        type: string
        default: 'clean install'

jobs:
  build:
    name: Build with Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        java: ${{ fromJSON(inputs.java_versions) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ inputs.java_distribution }}
          cache: maven

      - name: Build with Maven
        run: mvn --batch-mode ${{ inputs.maven_args }}

      - name: Get Artifact Name
        id: get_artifact_name
        run: echo $(mvn help:evaluate -Dexpression=project.name -q -DforceStdout) | tr '[:upper:]' '[:lower:]' | { read name; echo "artifact_name=$name" } >> $GITHUB_OUTPUT

      - name: Get Artifact Version
        id: get_artifact_version
        run: echo $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) | { read version; echo artifact_version=$version } >> $GITHUB_OUTPUT

      - name: Upload OMOD artifact
        if: matrix.java == inputs.main_java_version
        uses: actions/upload-artifact@v6
        with:
          name: ${{ steps.get_artifact_name.outputs.artifact_name }}-${{ steps.get_artifact_version.outputs.artifact_version }}
          path: omod/target/${{ steps.get_artifact_name.outputs.artifact_name }}-${{ steps.get_artifact_version.outputs.artifact_version }}.omod
          if-no-files-found: error